version: "3.9"

services:

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-angular
    depends_on:
      - sonardb
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

  sonardb:
    image: postgres:15
    container_name: sonar-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql/data

  # Herramienta que ejecuta el escaneo (Incluye Java 17+)
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    volumes:
      - .:/usr/src
    environment:
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_TOKEN=sqp_1a11ea16ba5d3643efc6032e46a42612740527dc
    depends_on:
      - sonarqube

volumes:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  sonar_db:
