name: CI/CD [Main]

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm ci

    - name: Build file
      run: npm run build

    - name: Deploy production to Netlify
      uses: jsmrcaga/action-netlify-deploy@v2.1.0
      with:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_DEPLOY_MESSAGE: 'DONE-DEPLOY'
        build_directory: dist
        build_command: npm run build
          
